### ISSUE TITLE
俊哥出品避属精品

### ISSUE THREAD

**Issue by nullkk** [li-xiaojun/StateLayout#1]
能出个java版本吗

**Comment by junixapp** [comment]
Java也可以调用啊，没有什么影响啊，孩子。

**Comment by teaim** [comment]
@li-xiaojun StateLayout.config()中的retryAction用java怎么传参, 我的找不到Function1这个函数, 是要开启kotlin支持吗

**Comment by junixapp** [comment]
@FreeLoopC 传递一个匿名函数，比如：
```java
new Function1<View, Unit>() {
                    @Override
                    public Unit invoke(View view) {
                        return null;
                    }
                }
```

**Comment by teaim** [comment]
@li-xiaojun 试了一下, 开启kotlin导入标准包之后就有了.
另外, 包裹按钮的时候, 加载布局必须要和按钮大小一致, 否则会出现重复背景的现象, 这点用起来不是很方便

**Comment by junixapp** [comment]
@FreeLoopC 这种场景需要你自定义加载布局啊，默认的加载布局肯定不能通用。
