### ISSUE TITLE
绑定Activity/Fragment 首次加载会有全屏遮挡

### ISSUE THREAD

**Issue by zhangjianzhu** [li-xiaojun/StateLayout#11]
如题 
每次在代码里执行加载效果，就会白屏或者黑屏全屏遮挡，再次通过点击事件加载会有地下的内容在，有个透明遮挡会有很多，如何做才能每次加载都是内容在底下，有个透明遮挡就好

**Comment by zhangjianzhu** [comment]
我现在的处理方法是延时1秒后加载就不会出现白屏/黑屏

**Comment by junixapp** [comment]
贴下代码
