### ISSUE TITLE
StateLayout用在Fragment时来回切换Fragment报异常

### ISSUE THREAD

**Issue by teaim** [li-xiaojun/StateLayout#4]
StateLayout用在Fragment时来回切换Fragment报异常

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

onCreateView里面重复wrap导致的

这种怎么解决

目前是判断stateLayout是否不为空, 不为空则跳过wrap

**Comment by junixapp** [comment]
贴下代码，应该是你写错了。

**Comment by teaim** [comment]
看了下你的示例代码,你这里对fragmentView进行了判空操作,所以不会重复wrap

if (fragmentView==null) {
    fragmentView = inflater.inflate(getLayoutId(), container, false)
    stateLayout = StateLayout(context!!)
            .wrap(fragmentView)
            .showLoading()
}
return stateLayout

我用的是局部变量view, 没有判空操作,所以会重复wrap.
后面我的解决方案是对stateLayout判空,和你这个一个意思

**Comment by junixapp** [comment]
@FreeLoopC 是的，Fragment的View一般都需要判空，不管用不用StateLayout。
