### ISSUE TITLE
有两个问题;约束布局和默认布局适配

### ISSUE THREAD

**Issue by o03150** [li-xiaojun/StateLayout#5]
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to androidx.constraintlayout.widget.ConstraintLayout$LayoutParams

1.如果xml根布局是约束布局,会报以上强转错误;

2.默认布局传入指定view,view的大小如果过小,会导致显示不全,能不能适配自动缩小点

3.有没有java库啊,kotlin没用过

**Comment by junixapp** [comment]
1. 这个是bug
2. 默认布局过小需要你自定义状态布局，就算自动缩小也会很难看
3. java可以直接用kotlin库
